# Day 3

## Numpy
-  Numpy stands for numerical python  
-  It is a python library used to work with arrays  
-  It also has functions to work with linear algebra,fourier transfroms,matrices etc  
-  Array object here is called N dimensional array,ndarray is 5x faster than lists in python

## Importing the library

In [5]:
import numpy as np

## Creating 1D array

In [6]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [7]:
print(type(a))

<class 'numpy.ndarray'>


In [8]:
a.ndim    #no.of dimensions of array

1

In [9]:
a.dtype   #data type of an array

dtype('int32')

In [10]:
a.shape   #shape of an array

(5,)

In [11]:
a.size    #no.of elements inside an array

5

In [12]:
a.itemsize  #each element size in bytes

4

In [13]:
a=np.array([1,2,3,4],np.int8)
a

array([1, 2, 3, 4], dtype=int8)

In [14]:
2**8-1

255

In [15]:
a=np.array([1,2,3,4,512],np.int8)
a

array([1, 2, 3, 4, 0], dtype=int8)

### Float

In [17]:
ar=np.array([10,20,30,69.8])
print(ar)
print(ar.dtype)

[10.  20.  30.  69.8]
float64


### String

In [18]:
b=np.array([100,78,56,'python'])
print(b)

['100' '78' '56' 'python']


In [23]:
dir(np.dtype)

['__bool__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'alignment',
 'base',
 'byteorder',
 'char',
 'descr',
 'fields',
 'flags',
 'hasobject',
 'isalignedstruct',
 'isbuiltin',
 'isnative',
 'itemsize',
 'kind',
 'metadata',
 'name',
 'names',
 'ndim',
 'newbyteorder',
 'num',
 'shape',
 'str',
 'subdtype',
 'type']

### Appending single element to an array

In [21]:
c=np.array([9,8,90])
c=np.append(c,34)
c

array([ 9,  8, 90, 34])

### Appending multiple elements to an array

In [22]:
c=np.append(c,[100,200,300])
c

array([  9,   8,  90,  34, 100, 200, 300])

### Creating ndarray using range()

In [26]:
r=np.array(range(1,9))       #start,stop
print(r)
print(type(r))

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


In [27]:
r=np.array(range(1,9,2))      #start,stop,step
print(r) 
print(type(r))

[1 3 5 7]
<class 'numpy.ndarray'>


### Creating ndarray using list[]

In [28]:
l=[90,89,72,56]
a=np.array(l)
print(a)
print(type(a))

[90 89 72 56]
<class 'numpy.ndarray'>


### Creating ndarray using arange()

In [30]:
a=np.arange(1,11)      #range of values
print(a)
print(type(a))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [32]:
a=np.arange(1,11,2)    #range of values with step value
print(a)
print(type(a))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [33]:
a.nbytes               #memory space occupied by array

20

In [35]:
print(len(a))          #length of array
print(a.itemsize)      #checkin each element size

5
4


In [36]:
print(np.arange(11,21))
print(np.arange(5))
print(np.arange(4,1))

[11 12 13 14 15 16 17 18 19 20]
[0 1 2 3 4]
[]


### Creating array using linspace

In [37]:
#creating array within given range with required no.of elements
a=np.linspace(1,10,20)     
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

### Creating array using logspace

In [38]:
#creating array within given range with required no.of elements with their log values
a=np.logspace(1,10,20)     
a

array([1.00000000e+01, 2.97635144e+01, 8.85866790e+01, 2.63665090e+02,
       7.84759970e+02, 2.33572147e+03, 6.95192796e+03, 2.06913808e+04,
       6.15848211e+04, 1.83298071e+05, 5.45559478e+05, 1.62377674e+06,
       4.83293024e+06, 1.43844989e+07, 4.28133240e+07, 1.27427499e+08,
       3.79269019e+08, 1.12883789e+09, 3.35981829e+09, 1.00000000e+10])

### Creating array using full

In [39]:
#repeating required no of times and making into array
np.full(10,"numpy")

array(['numpy', 'numpy', 'numpy', 'numpy', 'numpy', 'numpy', 'numpy',
       'numpy', 'numpy', 'numpy'], dtype='<U5')

In [40]:
np.full(10,'1,2')

array(['1,2', '1,2', '1,2', '1,2', '1,2', '1,2', '1,2', '1,2', '1,2',
       '1,2'], dtype='<U3')

### Creating array using ones

In [45]:
#repeat value of ones for required no.of times
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Creating array using zeros

In [44]:
#repeat value of ones for defined  no.of times
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Creating 2D Array

In [47]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(type(a))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>


In [49]:
print(a.ndim)
print(a.dtype)
print(a.nbytes)
print(a.itemsize)

2
int32
48
4


## Creating 3D Array
Combination of more no.of 2D arrays

In [54]:
a=np.array([[[9,8,7],[4,5,6]],[[1,2,3],[4,5,6]]])
a

array([[[9, 8, 7],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [55]:
print(type(a))
print(a.ndim)
print(a.dtype)
print(a.nbytes)
print(a.itemsize)

<class 'numpy.ndarray'>
3
int32
48
4


## Multidimensional Array

In [52]:
a=np.array([1,2,3,4,5],ndmin=20)
a

array([[[[[[[[[[[[[[[[[[[[1, 2, 3, 4, 5]]]]]]]]]]]]]]]]]]]])

In [56]:
print(type(a))
print(a.ndim)
print(a.dtype)
print(a.nbytes)
print(a.itemsize)

<class 'numpy.ndarray'>
3
int32
48
4


## Accessing Elements from an array

### Indexing:
-  Forward index  : starts from 0
-  Backward index : starts from -1 from backside

### 1D Array

In [57]:
a=np.array([10,202,30,40,50,60])
a

array([ 10, 202,  30,  40,  50,  60])

In [58]:
a[3]

40

In [59]:
a[-3]

40

In [60]:
a[-5]

202

In [61]:
a

array([ 10, 202,  30,  40,  50,  60])

In [62]:
a[1:4]    # 202,30,40

array([202,  30,  40])

In [63]:
a[::-1]   #reverse order

array([ 60,  50,  40,  30, 202,  10])

### 2D Array

In [64]:
b=np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [65]:
b.size

8

In [66]:
b.shape

(2, 4)

In [67]:
b[0]      #first row

array([1, 2, 3, 4])

In [68]:
b[1]     #second row

array([5, 6, 7, 8])

In [69]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [70]:
b[1,2]    #accessing particular element using row,column index

7

In [71]:
b[0][0]

1

In [72]:
b[:,0]    #1st column

array([1, 5])

In [73]:
b[:,-2]   #3rd column

array([3, 7])

In [74]:
b[:,-2:]   #row index slicing,element index slicing 

array([[3, 4],
       [7, 8]])

In [75]:
b[:,1:3]

array([[2, 3],
       [6, 7]])

### 3D Array

In [77]:
a=np.array([[[1,2,3,4],[5,6,7,8]],[[10,20,30,40],[50,60,70,80]]])
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[10, 20, 30, 40],
        [50, 60, 70, 80]]])

In [78]:
a[0]   #2d index

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [79]:
a[1]

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [80]:
a[0,0]

array([1, 2, 3, 4])

In [81]:
a[0,1]

array([5, 6, 7, 8])

In [84]:
a[1,0]

array([10, 20, 30, 40])

In [82]:
a[1,1]

array([50, 60, 70, 80])

In [87]:
a[1,1,2]

70

In [88]:
a[1,0,2]

30

In [89]:
a[0,0,-2]

3

In [90]:
a[:,0,-1]   #0th colum,-1 element

array([ 4, 40])

In [91]:
a[1,0,-1]

40

## Shape of an array

### 1D:

In [92]:
a=np.array([4,6,7])
a.shape

(3,)

### 2D:

In [94]:
b=np.array([[1,2,3],[4,5,6]])
b.shape

(2, 3)

### 3D:

In [95]:
c=np.array([[[1,2,3,4],[5,6,7,8]],[[10,20,30,40],[50,60,70,80]]])
c.shape

(2, 2, 4)

## Reshaping of array

In [98]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [99]:
b=a.reshape(4,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [100]:
b.ndim

2

In [101]:
a.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [102]:
a.reshape(2,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [103]:
a.reshape(10,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [104]:
a.reshape(2,2,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [105]:
a.reshape(2,5,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [107]:
a.reshape(4,-1)       #4rows,column is arranged by default

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [108]:
a.reshape(-1,5)      #4column

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [109]:
a.reshape(-1,2,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [110]:
a=np.arange(1,11).reshape(5,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

## TASK:
### Create array using numpy with all dimensions