# Day 5

## Random methods

In [2]:
import numpy as np

###  **randint** :Integer value with given range randomly

In [3]:
np.random.randint(140)     

60

### rand :float values within 0 and 1 range

In [4]:
np.random.rand()          

0.1896140194128051

### 1D array  with defined number of elements and size

In [5]:
np.random.randint(100,size=(20))   

array([11, 40, 74, 17, 14, 67, 64, 35, 39, 60, 18, 15, 42, 51, 64, 92, 98,
       33, 96, 55])

### 2D array  with defined number of elements and size

In [6]:
np.random.randint(50,size=(2,3))  #2d array

array([[ 3, 19, 25],
       [47,  7, 42]])

### 3D array  with defined number of elements and size

In [7]:
np.random.randint(10,size=(2,2,3))   #3d array

array([[[2, 7, 2],
        [6, 3, 4]],

       [[6, 3, 9],
        [6, 1, 3]]])

## Choice

In [8]:
np.random.choice([10,7,8,9,5])

5

In [12]:
np.random.choice([10,9,8,7,6,5],size=(3,2))

array([[ 7, 10],
       [ 8,  8],
       [ 7,  5]])

In [13]:
np.random.choice([10,9,8,7,6,5],size=(3,2,1))

array([[[ 8],
        [ 9]],

       [[10],
        [ 7]],

       [[ 5],
        [10]]])

### randn: positive and negative values in defined number

In [14]:
np.random.randn(10)

array([ 2.34750528, -1.8170593 ,  0.64778584,  0.9892904 ,  0.08076554,
       -0.85078439,  0.96083015,  0.75450369,  2.28928855, -0.03287827])

## Normal distribution

In [15]:
np.random.normal()

0.45673664751075754

## Array filtering

In [18]:
a=np.array([90,89,18,67,20])
b=[False,True,True,True,False]
c=a[b]
c

array([89, 18, 67])

**Print the values greater than 20**

In [19]:
#a=np.array([90,89,18,67,20])
#b=[True,True,False,True,False]

b=[]
for i in a:
    if i>20:
        b.append(True)
    else:
        b.append(False)

c=a[b]
c
        

array([90, 89, 67])

In [20]:
d=a>20
e=a[d]
e

array([90, 89, 67])

In [22]:
a.reshape(5,1)

array([[90],
       [89],
       [18],
       [67],
       [20]])

## Transpose

In [24]:
a.T

array([90, 89, 18, 67, 20])

# Pandas  
-  Pandas is a built in library used for data analysis
-  Used for data manipulations,visualisations,building machine learning models
-  There are two main data structures in pandas:   
    1)Series    
    2)Data frames

In [26]:
import pandas as pd

In [27]:
pd.__version__

'1.0.5'

### Pandas series  
-  A series is similar to 1D ARRAY and contains the value of same type.
-  Dataframe is simply a table where each column is a pandas series.  
-  Creating series:  
    *  List  
    *  Tuple  
    *  Dictionary  
    *  Numpy  
    *  Data_Range  
-  Series indexing

### Creating pandas series using List

In [28]:
l=[89,7,6,70,5,68]
p=pd.Series(l)
p

0    89
1     7
2     6
3    70
4     5
5    68
dtype: int64

### Creating pandas series using Tuple

In [33]:
t=(89,67,45)
s=pd.Series(t)
s

0    89
1    67
2    45
dtype: int64

In [34]:
p1=pd.Series(t,index=['a','b','c'])
p1

a    89
b    67
c    45
dtype: int64

### Creating pandas series using Dictionary

In [80]:
d={'amar':69,'bubblu':90,'vasu':78}
s=pd.Series(d)
s

amar      69
bubblu    90
vasu      78
dtype: int64

### Reindexing

In [81]:
s.index=[10,'a','b']     
s

10    69
a     90
b     78
dtype: int64

In [82]:
s['b']


78

In [40]:
s[10]

69

## Range

In [41]:
s[1:3]            #start,stop

a    90
b    78
dtype: int64

In [42]:
s

10    69
a     90
b     78
dtype: int64

In [44]:
s[1:4:2]          #start,stop,step

a    90
dtype: int64

In [45]:
s.index=[20,21,22]     
s

20    69
21    90
22    78
dtype: int64

In [53]:
s.index=np.arange(30,33)
s

30    69
31    90
32    78
dtype: int64

In [55]:
s=pd.Series("APSSDC",index=[1,2,3,4])
s

1    APSSDC
2    APSSDC
3    APSSDC
4    APSSDC
dtype: object

## Squares of first 10 natural numbers

In [56]:
s=pd.Series([i**2 for i in range(11)])
s

0       0
1       1
2       4
3       9
4      16
5      25
6      36
7      49
8      64
9      81
10    100
dtype: int64

In [59]:
n=int(input())
s=pd.Series([i**2 for i in range(1,n+1)],
            index=list(range(1,n+1)))
s


8


1     1
2     4
3     9
4    16
5    25
6    36
7    49
8    64
dtype: int64

## Dictionary Comprehension

In [67]:
n=int(input())
s={i:i**2 for i in range(1,n+1)}
p=pd.Series(d)
p

6


1     1
2     4
3     9
4    16
5    25
6    36
7    49
8    64
dtype: int64

In [78]:
s=pd.Series(np.square(np.arange(1,10)))
s.index=range(1,10)
s

1     1
2     4
3     9
4    16
5    25
6    36
7    49
8    64
9    81
dtype: int32

## Date Range Method

In [79]:
dates=pd.date_range(start="2020-10-5",end="2020-10-12")
dates

DatetimeIndex(['2020-10-05', '2020-10-06', '2020-10-07', '2020-10-08',
               '2020-10-09', '2020-10-10', '2020-10-11', '2020-10-12'],
              dtype='datetime64[ns]', freq='D')

In [84]:
help(pd.date_range)

Help on function date_range in module pandas.core.indexes.datetimes:

date_range(start=None, end=None, periods=None, freq=None, tz=None, normalize=False, name=None, closed=None, **kwargs) -> pandas.core.indexes.datetimes.DatetimeIndex
    Return a fixed frequency DatetimeIndex.
    
    Parameters
    ----------
    start : str or datetime-like, optional
        Left bound for generating dates.
    end : str or datetime-like, optional
        Right bound for generating dates.
    periods : int, optional
        Number of periods to generate.
    freq : str or DateOffset, default 'D'
        Frequency strings can have multiples, e.g. '5H'. See
        :ref:`here <timeseries.offset_aliases>` for a list of
        frequency aliases.
    tz : str or tzinfo, optional
        Time zone name for returning localized DatetimeIndex, for example
        'Asia/Hong_Kong'. By default, the resulting DatetimeIndex is
        timezone-naive.
    normalize : bool, default False
        Normalize start/

## Creating series by using numpy array

In [85]:
n=np.arange(10)
n

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
s=pd.Series(n,index=np.arange(20,30))
s

20    0
21    1
22    2
23    3
24    4
25    5
26    6
27    7
28    8
29    9
dtype: int32

In [87]:
n1=np.array([23,67,8,9,90])
n1

array([23, 67,  8,  9, 90])

In [89]:
s1=pd.Series(n1)
s1

0    23
1    67
2     8
3     9
4    90
dtype: int32

In [94]:
s2=pd.Series(np.array([90,89,87,67]),index=['a','b','c','d'])
s2

a    90
b    89
c    87
d    67
dtype: int32

In [96]:
s

0    23
1    67
2     8
3     9
4    90
dtype: int32

In [97]:
s[0:2]

0    23
1    67
dtype: int32

## Fancy Indexing

In [101]:
s[[26,27,28]]

26    6
27    7
28    8
dtype: int32

In [105]:
d={"a":45,"b":46,"c":78,"d":np.nan,"y":"abc"}
s=pd.Series(d)
s

a     45
b     46
c     78
d    NaN
y    abc
dtype: object

In [106]:
s["d"]

nan

In [107]:
s["d"]=787           #assigning value to a nan value

In [108]:
s

a     45
b     46
c     78
d    787
y    abc
dtype: object